config/routes.rb
Rails.application.routes.draw do
  root 'main#info'
  get 'main/index'
  get 'main/switch'
  get 'main/bla'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def info
  end

  def switch
    @bla = 'bla bla'
    render template: 'main/bla'
  end

end


def index
  @films = Film.select('Title, Year').order('created_at DESC')
  render template: 'view/films'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/main/bla.html.erb
<p><%= @bla %></p>

app/views/main/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#about" aria-controls="about" role="tab" data-toggle="tab">
      About
    </a>
  </li>
  <li role="presentation">
    <a href="#advertise" aria-controls="advertise" role="tab" data-toggle="tab">
      Advertise
    </a>
  </li>
  <li role="presentation">
    <a href="#legal" aria-controls="legal" role="tab" data-toggle="tab">
      Legal
    </a>
  </li>
  <li role="presentation">
    <a href="#privacy" aria-controls="privacy" role="tab" data-toggle="tab">
      Privacy
    </a>
  </li>
  <li role="presentation" id="terms-li">
    <a href="#terms-tab" aria-controls="terms" role="tab" data-toggle="tab">
      Terms
    </a>
  </li>
</ul>

<div class="tab-content" id="infoTabContent">
  <div role="tabpanel" class="tab-pane fade in active" id="about">
    <h3>About</h3>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="advertise">
    <h3>Advertise</h3>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="legal">
    <h3>Legal</h3>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="privacy">
    <h3>Privacy</h3>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="terms-tab">
    <h3>Terms</h3>
  </div>
</div>

<%= link_to 'Go back', root_path %>

<script>
  if ('<%= params[:tab] %>' !== '') { 
    let params = '<%= params[:tab] %>',
        li = document.getElementById(params + '-li'),
        tab = document.getElementById(params + '-tab'),
        ul = document.querySelectorAll('ul.nav.nav-tabs > li')[0].classList,
        div = document.querySelectorAll('div.tab-content > div')[0].classList
    
    ul.remove('active')
    div.remove('in', 'active')
    li.classList.add('active')
    tab.classList.add('in', 'active')
  }
</script>

app/views/main/info.html.erb
<p>
  View the terms & conditions on our info page 
  <%= link_to 'here', main_index_path(tab: 'terms') %>, thanks.
</p>